#include <main.h>

void main() {
   //Initialize the system
   init();
    
   //The ammount of tries the player has
   int8 health = 1;
   
   //Starting minutes and seconds
   int8 min = 4;
   int8 sec = 0;
   
   //How many modules left to solve
   int8 modules_left = 2;
   
   //Turn on or off randomly 4 leds
   int8 series[8];
   led_series_set(series);
   
   //Wait and send data to all modules
   delay_ms(500);
   send_gen_values(series, health, min, sec);
   
   while (TRUE) {
      //Displays and counts the numbers
      display_loop(min, sec, health);
      
      //Check if all modules are solved
      if(modules_left <= 0){
         //display_loop(
         break;
      }
      
      //Beeping sound generation and time setting
      beep_sound(min, sec);
      
      //Main game check if the player failed
      if(check_fail_state(min, sec, health) == 1){
         break;
      }
      
      //Send data to modules (time, hp...)
      send_gen_values(series, health, min, sec);
      
      //Check if HP is reduced from modules
      recieve_hp_data(health, modules_left);
   }

}

//Checks if HP is reduced from modules
void recieve_hp_data(int8 &health, int8 &modules_left){
   //Data to be gathered from modules
   //0 = nothing, -1 = reduce hp, 1 = module solved
   
   //SLAVE 1---------------------------------------------
   int8 incoming = 0;
   
   i2c_start(); 
   i2c_write(SLAVE1_READ_ADDR); 
   incoming = i2c_read(0); 
   i2c_stop(); 
   
   if(incoming == -1){
      health -= 1;
   }
   if(incoming == 1){
      modules_left -= 1;
   }
   //----------------------------------------------------
   
   //SLAVE 2---------------------------------------------
   /*incoming = 0;
   
   i2c_start(); 
   i2c_write(SLAVE2_READ_ADDR); 
   incoming = i2c_read(0); 
   i2c_stop(); 
   
   if(incoming == -1){
      health -= 1;
   }
   if(incoming == 1){
      modules_left -= 1;
   }*/
   //----------------------------------------------------
   
}

void send_gen_values(int8 series[], int8 health, int8 min, int8 sec){   
   int bin;
   int i;
   for (bin = 0, i = 0; i < 8; ++i ){
      bin = bin << 1;
      bin = bin + series[i];
   }
   
   i2c_start();
   i2c_write(SLAVE1_WRT_ADDR);
   i2c_write(health);
   i2c_write(min);
   i2c_write(sec);
   i2c_write(bin);
   
   i2c_start();
   i2c_write(SLAVE2_WRT_ADDR);
   i2c_write(health);
   i2c_write(min);
   i2c_write(sec);
   i2c_write(bin);
   
   i2c_stop();
   
}

//Set debug leds randomly
void led_series_set(int8 series[]){
   //Set a random pattern to the leds
   for(int i = 0; i < 4; i++){
      series[i] = (rand() % 2);
   }
   
   //Set the leds to the pattern
   if(series[0] == 1){
      output_high(led1);
   }
   if(series[1] == 1){
      output_high(led2);
   }
   if(series[2] == 1){
      output_high(led3);
   }
   if(series[3] == 1){
      output_high(led4);
   }
   series[4] = 0;
   series[5] = 0;
   series[6] = 0;
   series[7] = 0;
}

//Initialize the system
void init(void){
   //This buzzer pins, snd2 always gnd
   output_low(snd2);
   output_low(snd1);
   
   //Debug leds
   output_low(led1);
   output_low(led2);
   output_low(led3);
   output_low(led4);
   
   //Generation of the seed
   seed_generation();
   
   //Reset displays
   reset();
}

//Generation of the seed
void seed_generation(void){
   //The seed is generated by counting how many times the system turned on
   write_eeprom(0, read_eeprom(0));
   srand(read_eeprom(0));
   write_eeprom(0, read_eeprom(0) + 0x1);
   
   //If the eeprom value is almost greater then a 8bit value, start counting
   //from 0, to prevent overflow
   if(read_eeprom(0) >= 255){
      write_eeprom(0, 0x0);
   }
}

//Beeping sound generation
void beep_sound(int8 min, int8 sec){
  if(min > 0 || sec > 30){
      output_high(snd1);
      delay_ms(1);
      output_low(snd1);
      delay_ms(999);
   }else if(sec <= 30 && sec > 10){
      output_high(snd1);
      delay_ms(1);
      output_low(snd1);
      delay_ms(499);
      output_high(snd1);
      delay_ms(1);
      output_low(snd1);
      delay_ms(499);
   }else if(sec <= 10 && sec >= 1){
      output_high(snd1);
      delay_ms(1);
      output_low(snd1);
      delay_ms(332);
       output_high(snd1);
      delay_ms(1);
      output_low(snd1);
      delay_ms(332);
      output_high(snd1);
      delay_ms(1);
      output_low(snd1);
      delay_ms(332);
   }else if(sec == 0){
      output_high(snd1);
      delay_ms(1000);
      output_low(snd1);
   }
}

//Main game check if the player failed
int8 check_fail_state(int8 &min, int8 &sec, int8 health){
   if((min == 0 && sec == 0) || (health <= 0)){
      return 1;
   }
   if(sec == 0){
      min -= 1;
      sec = 59;
      return 0;
   }
   sec -= 1;
   return 0;
}

//Sets the needed 7-segment's digit
void display(int8 digit, int8 data_pin, int8 segment){
   int8 state = 0;    //Whether to output_high or output_low
   
   //Chooses which number to display
   if(digit == 0){
      state = disp0[segment];
   }else if(digit == 1){
      state = disp1[segment];
   }else if(digit == 2){
      state = disp2[segment];
   }else if(digit == 3){
      state = disp3[segment];
   }else if(digit == 4){
      state = disp4[segment];
   }else if(digit == 5){
      state = disp5[segment];
   }else if(digit == 6){
      state = disp6[segment];
   }else if(digit == 7){
      state = disp7[segment];
   }else if(digit == 8){
      state = disp8[segment];
   }else if(digit == 9){
      state = disp9[segment];
   }
   
   //If the digit is for the first seven segment, set it so.
   if(data_pin == ser1 && state == 1){
      output_high(ser1);
   }else if(data_pin == ser2 && state == 1){
      output_high(ser2);
   }else if(data_pin == ser3 && state == 1){
      output_high(ser3);
   }else if(data_pin == ser4 && state == 1){
      output_high(ser4);
   }else if(data_pin == ser5 && state == 1){
      output_high(ser5);
   }
}

//Seperates the numbers, ex 23 -> 2 and 3
void seperateNumbers(int8 &min1, int8 &min2, int8 &sec1, int8 &sec2, int8 min, int8 sec){
   min1 = min / 10;
   min2 = min % 10;
   sec1 = sec / 10;
   sec2 = sec % 10;
}

//Starts calculating the digits for the 7-segments
void display_loop(int8 &min, int8 &sec, int8 &health) {
   int8 min1 = 0;   //First digit of the min var. etc...
   int8 min2 = 0;
   int8 sec1 = 0;
   int8 sec2 = 0;
   seperateNumbers(min1, min2, sec1, sec2, min, sec);
   for(int i = 0; i < 8; i++) {
      display(min1, ser1, i);
      display(min2, ser2, i);
      display(sec1, ser3, i);
      display(sec2, ser4, i);
      display(health, ser5, i);
      
      output_high(shclk);
      output_low(shclk);
      
      output_low(ser1);
      output_low(ser2);
      output_low(ser3);
      output_low(ser4); 
      output_low(ser5);
   }
   output_high(strclk);
   output_low(strclk);
}

//Resets all of the 7-segments to zero
void reset() {
   output_low(ser1);
   output_low(ser2);
   output_low(ser3);
   output_low(ser4);   
   output_low(ser5);
   
   for(int i = 0; i < 8; i++) {
      output_high(shclk);
      output_high(strclk);
      output_low(shclk);
      output_low(strclk);
   }
}

